import { shippedConfig } from "../lib/repo-config.ts";
import assert from "node:assert/strict";
import { afterEach, beforeEach, describe, it } from "node:test";
import type {
  ExtensionAPI,
  ToolCallEvent,
  ToolCallEventResult,
} from "@earendil-works/pi-coding-agent";
import { buildRules, GUARD_VERSION, id, register } from "../../extensions/guard.ts";
import { resetSurfaced } from "../../extensions/lib/once.ts";
import { bashEvent, fakeCtx, recorder, testPolicy } from "./helpers.ts";

/** The six gates, in order. `ALW` was the seventh until the 2026-08-14 deny-list inversion. Two of
 *  these block (`DB`, `GIT`); the other four only observe. `SEC` keeps its leading position after
 *  the 2026-08-15 demotion because order still decides which id a match is reported under, and a
 *  credential path is the more informative answer than whatever a later gate noticed. */
const GATES = ["SEC", "DB", "GIT", "PRV", "FS", "RTE"];

type Handler = (
  event: ToolCallEvent,
  ctx: ReturnType<typeof fakeCtx>,
) => Promise<ToolCallEventResult | undefined>;

interface FakePi {
  pi: ExtensionAPI;
  handlers: Handler[];
  entries: Array<[string, unknown]>;
  emitted: Array<[string, unknown]>;
  renderers: string[];
}

function fakePi(): FakePi {
  const handlers: Handler[] = [];
  const entries: Array<[string, unknown]> = [];
  const emitted: Array<[string, unknown]> = [];
  const renderers: string[] = [];
  const pi = {
    on(event: string, handler: Handler) {
      if (event === "tool_call") handlers.push(handler);
    },
    appendEntry(customType: string, data: unknown) {
      entries.push([customType, data]);
    },
    registerEntryRenderer(customType: string) {
      renderers.push(customType);
    },
    events: {
      emit(channel: string, data: unknown) {
        emitted.push([channel, data]);
      },
      on: () => () => {},
    },
  } as unknown as ExtensionAPI;
  return { pi, handlers, entries, emitted, renderers };
}

/**
 * A `pi` whose `events` is a real (if tiny) bus: listeners are kept and `emit` dispatches to them.
 * `fakePi` above only records emits, which cannot observe an ask-and-answer round trip.
 */
function fakeBusPi(): {
  pi: ExtensionAPI;
  bus: { on(channel: string, listener: (data: unknown) => void): void; emit(channel: string, data: unknown): void };
} {
  const listeners = new Map<string, Array<(data: unknown) => void>>();
  const bus = {
    on(channel: string, listener: (data: unknown) => void) {
      const list = listeners.get(channel) ?? [];
      list.push(listener);
      listeners.set(channel, list);
      return () => undefined;
    },
    emit(channel: string, data: unknown) {
      for (const listener of [...(listeners.get(channel) ?? [])]) listener(data);
    },
  };
  const pi = {
    on: () => {},
    appendEntry: () => {},
    registerEntryRenderer: () => {},
    events: bus,
  } as unknown as ExtensionAPI;
  return { pi, bus };
}

beforeEach(() => {
  resetSurfaced();
  delete process.env.PI_GUARD_TEST_THROW;
  // `config/guard.json` is generated by scripts/install.sh and git-ignored, so it does not exist on
  // a clean checkout; `register()` would then load its built-in defaults and report `degraded: true`.
  // Pin the loader at whichever of the two the checkout actually has — the tracked template on CI,
  // the generated file on an installed machine — so the handshake assertion tests the handshake.
  process.env.PI_GUARD_POLICY = shippedConfig("guard");
});
afterEach(() => {
  delete process.env.PI_GUARD_TEST_THROW;
  delete process.env.PI_GUARD_POLICY;
});

describe("guard.register", () => {
  it("binds exactly one tool_call handler — event 30 is the only one used", () => {
    const { pi, handlers } = fakePi();
    register(pi);
    assert.equal(handlers.length, 1);
  });

  it("emits the guard:ready handshake trust.ts's deadman and doctor's D-06 consume", () => {
    const { pi, emitted } = fakePi();
    register(pi);
    const ready = emitted.find(([channel]) => channel === "guard:ready");
    assert.ok(ready);
    const payload = ready[1] as { version: string; gates: string[]; degraded: boolean };
    assert.equal(payload.version, GUARD_VERSION);
    assert.equal(payload.degraded, false);
    assert.deepEqual(payload.gates, GATES);
  });

  it("answers guard:whois by re-emitting guard:ready — wave1-specs.md §7.2's round trip", () => {
    // EXT-30 hand-off T1. `pi.events` is a bare EventBus with no replay buffer and `guard`
    // registers FIRST in index.ts's ORDER, so the start-up emit is missed by every subscriber.
    // Asking is the only way to see it; before this listener existed, trust.ts's and doctor.ts's
    // `guard:whois` emits went nowhere and their `guard:ready` handlers never fired.
    const { pi, bus } = fakeBusPi();
    register(pi);
    const seen: unknown[] = [];
    bus.on("guard:ready", (data) => seen.push(data));
    assert.deepEqual(seen, [], "a late subscriber sees nothing until it asks");

    bus.emit("guard:whois", {});
    assert.equal(seen.length, 1, "the answer must arrive synchronously");
    const payload = seen[0] as { version: string; gates: string[] };
    assert.equal(payload.version, GUARD_VERSION);
    assert.deepEqual(payload.gates, GATES);
  });

  it("answers guard:whois every time, not once — two subscribers must both be servable", () => {
    const { pi, bus } = fakeBusPi();
    register(pi);
    let answers = 0;
    bus.on("guard:ready", () => answers++);
    bus.emit("guard:whois", {});
    bus.emit("guard:whois", {});
    assert.equal(answers, 2);
  });

  it("id is stable", () => {
    assert.equal(id, "guard");
  });

  it("blocks through the registered handler and writes one guard.block entry", async () => {
    const { pi, handlers, entries, renderers } = fakePi();
    register(pi);
    // The entry is only half of it: without a renderer for that type the denial paints as
    // PI's generic custom-entry fallback instead of the card.
    assert.ok(renderers.includes("guard.block"), "guard.block has no renderer");
    const result = await handlers[0]!(bashEvent("rm -rf ~"), fakeCtx());
    assert.equal(result?.block, true);
    assert.match(result?.reason ?? "", /^Blocked by gate DB-RM-ROOT:/);
    const blocks = entries.filter(([type]) => type === "guard.block");
    assert.equal(blocks.length, 1);
    const entry = blocks[0]![1] as { ruleId: string; reason: string };
    // `guardedHandler` audits `rule.id`, which is the gate FAMILY. The specific pattern id is
    // only in the reason string — see the manifest's open question on this.
    assert.equal(entry.ruleId, "DB");
    assert.match(entry.reason, /DB-RM-ROOT/);
  });

  it("register() does nothing async and starts no timers (wave1-specs 3.2)", () => {
    const { pi } = fakePi();
    const before = process.getActiveResourcesInfo().length;
    register(pi);
    assert.equal(process.getActiveResourcesInfo().length, before);
  });

  it("gate order is the policy: cheapest and most absolute first", () => {
    const rec = recorder();
    assert.deepEqual(buildRules(testPolicy(), rec.services).map((r) => r.id), GATES);
  });

  it("the allow-list gate is gone, not merely reordered", () => {
    const rec = recorder();
    const ids = buildRules(testPolicy(), rec.services).map((r) => r.id);
    assert.equal(ids.includes("ALW"), false);
  });

  it("F2: only DB fails CLOSED on an internal error; SEC/GIT/PRV/FS/RTE stay on the shared default", () => {
    // `SEC` carried `"closed"` until 2026-08-15, when it stopped blocking. The reasoning that put
    // it there — "this rule's absence IS the unsafe state" — inverted with the demotion: a gate
    // that cannot refuse anything has nothing to protect by refusing everything, so a bug in it
    // would buy an outage for one missing audit line. `DB` still blocks, so it still fails closed.
    const rec = recorder();
    const byId = new Map(buildRules(testPolicy(), rec.services).map((r) => [r.id, r]));
    assert.equal(byId.get("DB")?.onInternalError, "closed");
    for (const id of ["SEC", "GIT", "PRV", "FS", "RTE"]) {
      assert.equal(byId.get(id)?.onInternalError, undefined, id);
    }
  });

  it("REQ-EXT-16: a throwing audit-only gate does NOT refuse the call, and still reports every time", async () => {
    const { pi, handlers } = fakePi();
    register(pi);
    // A malformed `ctx.cwd` (not a string) makes `collectTargets`'s `path.resolve` throw —
    // exactly the class of internal error REQ-EXT-16 describes, reachable through SEC's real
    // code path rather than a synthetic injected rule. Before 2026-08-15 this refused the call;
    // now the bug costs the SEC audit line for that call and nothing else, which is the whole
    // point of not failing closed in a gate that cannot block.
    const brokenCtx = {
      hasUI: false,
      mode: "print",
      cwd: undefined,
      ui: { notify() {} },
    } as unknown as ReturnType<typeof fakeCtx>;

    const first = await handlers[0]!(bashEvent("cat foo.txt"), brokenCtx);
    assert.notEqual(first?.block, true, "an audit-only gate's bug must not refuse the tool call");

    const second = await handlers[0]!(bashEvent("cat bar.txt"), brokenCtx);
    assert.notEqual(second?.block, true, "and must not start refusing on the second occurrence");
  });
});
