import { shippedConfig } from "../lib/repo-config.ts";
import assert from "node:assert/strict";
import { mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, it } from "node:test";
import { DEFAULT_POLICY, loadPolicy } from "../../extensions/guard/policy.ts";

function scratch(): string {
  return mkdtempSync(join(process.env.TMPDIR ?? tmpdir(), "pi-guard-policy-"));
}

afterEach(() => {
  delete process.env.PI_GUARD_POLICY;
});

/**
 * `config/guard.json` is generated by `scripts/install.sh` from `config/guard.default.json` and is
 * git-ignored, so a clean checkout has only the template. `shippedConfig("guard")` resolves to whichever
 * of the two exists — the template in CI, the operator's generated file on an installed machine —
 * and both must satisfy every assertion below, because the installer copies one to the other.
 */
const SHIPPED_GUARD = shippedConfig("guard");

describe("loadPolicy", () => {
  it("loads the shipped guard policy and is not degraded", () => {
    const policy = loadPolicy(SHIPPED_GUARD);
    assert.equal(policy.degraded, false, policy.problem);
    assert.equal(policy.problem, undefined);
    assert.match(policy.source, /config\/guard(\.default)?\.json$/);
  });

  it("the shipped file and the built-in defaults agree — no drifting second copy", () => {
    const shipped = loadPolicy(SHIPPED_GUARD);
    assert.deepEqual(shipped.protectedBranches, DEFAULT_POLICY.protectedBranches);
    assert.deepEqual(shipped.dispatchTools, DEFAULT_POLICY.dispatchTools);
  });

  it("carries exactly two keys — the deny-list is code, not data (2026-08-14 inversion)", () => {
    // The regression this guards against is the allow-list growing back. It was removed as a
    // concept, not shortened: there is no key here a future edit can extend to re-admit
    // decide-by-program-name. Anything new appearing in the shipped file is a design change and
    // has to be argued for, not slipped in.
    const shipped = JSON.parse(readFileSync(SHIPPED_GUARD, "utf8")) as Record<string, unknown>;
    assert.deepEqual(Object.keys(shipped).sort(), ["dispatchTools", "protectedBranches"]);
  });

  it("has no allowlist and no nonInteractive mode, in the file or in the defaults", () => {
    const shipped = JSON.parse(readFileSync(SHIPPED_GUARD, "utf8")) as Record<string, unknown>;
    for (const dead of ["allowlist", "nonInteractive", "approvalUi", "confirmTimeoutMs",
      "escalation", "escalationEnv", "escalationValue", "remoteAllowlist"]) {
      assert.equal(shipped[dead], undefined, dead);
      assert.equal((DEFAULT_POLICY as unknown as Record<string, unknown>)[dead], undefined, dead);
    }
  });

  it("protects main and master by default — the only branch names GIT-FORCE-PROTECTED knows", () => {
    assert.deepEqual([...loadPolicy(SHIPPED_GUARD).protectedBranches].sort(), ["main", "master"]);
  });

  it("a missing file degrades LOUDLY and keeps the built-in defaults", () => {
    const policy = loadPolicy(join(scratch(), "absent.json"));
    assert.equal(policy.degraded, true);
    assert.match(policy.problem ?? "", /not found/);
    // Degradation no longer weakens anything that blocks: SEC/DB/GIT live in code. The message
    // has to say so, because the old message said the opposite and operators read it.
    assert.match(policy.problem ?? "", /deny-list is in code and is unaffected/);
    assert.deepEqual(policy.protectedBranches, DEFAULT_POLICY.protectedBranches);
  });

  it("malformed JSON degrades LOUDLY rather than silently allowing everything", () => {
    const dir = scratch();
    const file = join(dir, "guard.json");
    writeFileSync(file, "{ not json");
    const policy = loadPolicy(file);
    assert.equal(policy.degraded, true);
    assert.match(policy.problem ?? "", /not valid JSON/);
    assert.match(policy.problem ?? "", /deny-list is in code and is unaffected/);
  });

  it("a non-object policy is refused", () => {
    const file = join(scratch(), "guard.json");
    writeFileSync(file, "[]");
    const policy = loadPolicy(file);
    assert.equal(policy.degraded, true);
    assert.match(policy.problem ?? "", /must be a JSON object/);
  });

  it("reports a bad field without discarding the rest of the file", () => {
    const file = join(scratch(), "guard.json");
    writeFileSync(file, JSON.stringify({ protectedBranches: ["release"], dispatchTools: "task" }));
    const policy = loadPolicy(file);
    assert.equal(policy.degraded, false);
    assert.match(policy.problem ?? "", /"dispatchTools" must be an array of strings/);
    assert.deepEqual(policy.dispatchTools, DEFAULT_POLICY.dispatchTools);
    assert.deepEqual(policy.protectedBranches, ["release"]);
  });

  it("names an unknown key instead of ignoring it", () => {
    const file = join(scratch(), "guard.json");
    writeFileSync(file, JSON.stringify({ protectedBranches: [], allowlist: ["git"] }));
    // `allowlist` is now exactly as unknown as a typo. That is the point: a config that still
    // carries one is reported, not quietly honoured and not quietly dropped.
    assert.match(loadPolicy(file).problem ?? "", /unknown key "allowlist"/);
  });

  it("PI_GUARD_POLICY wins over the shipped file", () => {
    const file = join(scratch(), "guard.json");
    writeFileSync(file, JSON.stringify({ protectedBranches: ["only-this"] }));
    process.env.PI_GUARD_POLICY = file;
    assert.deepEqual(loadPolicy().protectedBranches, ["only-this"]);
  });
});
