import { shippedConfig } from "../lib/repo-config.ts";
import assert from "node:assert/strict";
import { mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, it } from "node:test";
import { DEFAULT_POLICY, loadPolicy } from "../../extensions/guard/policy.ts";

function scratch(): string {
  return mkdtempSync(join(process.env.TMPDIR ?? tmpdir(), "pi-guard-policy-"));
}

afterEach(() => {
  delete process.env.PI_GUARD_POLICY;
});

/**
 * `config/guard.json` is generated by `scripts/install.sh` from `config/guard.default.json` and is
 * git-ignored, so a clean checkout has only the template. `shippedConfig("guard")` resolves to whichever
 * of the two exists — the template in CI, the operator's generated file on an installed machine —
 * and both must satisfy every assertion below, because the installer copies one to the other.
 */
const SHIPPED_GUARD = shippedConfig("guard");

describe("loadPolicy", () => {
  it("loads the shipped guard policy and is not degraded", () => {
    const policy = loadPolicy(SHIPPED_GUARD);
    assert.equal(policy.degraded, false, policy.problem);
    assert.equal(policy.problem, undefined);
    assert.match(policy.source, /config\/guard(\.default)?\.json$/);
  });

  it("the shipped file and the built-in defaults agree — no drifting second copy", () => {
    const shipped = loadPolicy(SHIPPED_GUARD);
    assert.deepEqual([...shipped.allowlist].sort(), [...DEFAULT_POLICY.allowlist].sort());
    assert.equal(shipped.nonInteractive, DEFAULT_POLICY.nonInteractive);
    assert.equal(shipped.escalationEnv, DEFAULT_POLICY.escalationEnv);
    assert.equal(shipped.escalationValue, DEFAULT_POLICY.escalationValue);
    assert.deepEqual(shipped.protectedBranches, DEFAULT_POLICY.protectedBranches);
    assert.deepEqual(shipped.dispatchTools, DEFAULT_POLICY.dispatchTools);
  });

  it("ships the allowlist as data, exactly as implementation_plan.md 4.3 lists it", () => {
    const policy = loadPolicy(SHIPPED_GUARD);
    for (const program of ["git", "npm", "npx", "node", "uv", "uvx", "python", "pytest", "ruff",
      "mypy", "sleep", "echo", "cat", "ls", "rg", "fd", "jq", "make", "docker", "gh"]) {
      assert.ok(policy.allowlist.has(program), program);
    }
    assert.equal(policy.allowlist.size, 20);
  });

  it("a missing file degrades LOUDLY and keeps the built-in defaults", () => {
    const policy = loadPolicy(join(scratch(), "absent.json"));
    assert.equal(policy.degraded, true);
    assert.match(policy.problem ?? "", /not found/);
    assert.match(policy.problem ?? "", /allowlist is treated as EMPTY/);
  });

  it("malformed JSON degrades LOUDLY rather than silently allowing everything", () => {
    const dir = scratch();
    const file = join(dir, "guard.json");
    writeFileSync(file, "{ not json");
    const policy = loadPolicy(file);
    assert.equal(policy.degraded, true);
    assert.match(policy.problem ?? "", /not valid JSON/);
  });

  it("a non-object policy is refused", () => {
    const file = join(scratch(), "guard.json");
    writeFileSync(file, "[]");
    const policy = loadPolicy(file);
    assert.equal(policy.degraded, true);
    assert.match(policy.problem ?? "", /must be a JSON object/);
  });

  it("reports a bad field without discarding the rest of the file", () => {
    const file = join(scratch(), "guard.json");
    writeFileSync(file, JSON.stringify({ allowlist: ["git"], nonInteractive: "sometimes" }));
    const policy = loadPolicy(file);
    assert.equal(policy.degraded, false);
    assert.match(policy.problem ?? "", /"nonInteractive" must be one of/);
    assert.equal(policy.nonInteractive, "allowlist-only");
    assert.deepEqual([...policy.allowlist], ["git"]);
  });

  it("names an unknown key instead of ignoring it", () => {
    const file = join(scratch(), "guard.json");
    writeFileSync(file, JSON.stringify({ allowlist: [], allowlst: ["git"] }));
    assert.match(loadPolicy(file).problem ?? "", /unknown key "allowlst"/);
  });

  it("parses the plan's one-string escalation form", () => {
    const file = join(scratch(), "guard.json");
    writeFileSync(file, JSON.stringify({ escalation: "MY_VAR=yes" }));
    const policy = loadPolicy(file);
    assert.equal(policy.escalationEnv, "MY_VAR");
    assert.equal(policy.escalationValue, "yes");
  });

  it("PI_GUARD_POLICY wins over the shipped file", () => {
    const file = join(scratch(), "guard.json");
    writeFileSync(file, JSON.stringify({ allowlist: ["only-this"] }));
    process.env.PI_GUARD_POLICY = file;
    assert.deepEqual([...loadPolicy().allowlist], ["only-this"]);
  });
});
