// EXT-13 (c) — provider error surfacing, the deliverable that replaced the cancelled EXT-08.
//
// What these tests are actually protecting: the three rules —
// no substitution, no truncation, non-zero exit in print mode — plus the classification table
// that turns a provider failure into one of the classes the routing table fixes.
import { shippedConfig } from "./lib/repo-config.ts";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { describe, it } from "node:test";

import {
  buildEmptyCompletionFailure,
  buildProviderFailure,
  classifyProviderError,
  formatDiagnostics,
  formatProviderFailure,
  isEmptyCompletion,
  pickGatewayHeaders,
  PROVIDER_FAILURE_MARKER,
  summariseProviderFailure,
  surfaceProviderFailure,
  type ProviderErrorClass,
} from "../extensions/lib/provider-error.ts";

// `config/routing.json` is generated by scripts/install.sh and git-ignored; the contract below is a
// property of the tracked template every install starts from.
const ROUTING_PATH = shippedConfig("routing");

describe("classifyProviderError", () => {
  const table: Array<{
    name: string;
    input: Parameters<typeof classifyProviderError>[0];
    expected: ProviderErrorClass;
  }> = [
    // --- auth -------------------------------------------------------------------------------
    { name: "401", input: { status: 401, message: "Unauthorized" }, expected: "auth" },
    { name: "403 with no policy signal", input: { status: 403, message: "Forbidden" }, expected: "auth" },
    {
      name: "expired credential with no status (the dbx-token-cached failure mode)",
      input: { message: "the token has expired; run `databricks auth login`" },
      expected: "auth",
    },
    {
      name: "PI's own missing-key message",
      input: { message: 'No API key found for "databricks"' },
      expected: "auth",
    },

    // --- quota ------------------------------------------------------------------------------
    { name: "429", input: { status: 429, message: "Too Many Requests" }, expected: "quota" },
    { name: "402", input: { status: 402, message: "Payment Required" }, expected: "quota" },
    {
      name: "credit balance at status 400",
      input: { status: 400, message: "Your credit balance is too low to access this model" },
      expected: "quota",
    },

    // --- model-not-found --------------------------------------------------------------------
    { name: "404", input: { status: 404, message: "Not Found" }, expected: "model-not-found" },
    {
      name: "the Databricks endpoint-name trap (V-30) arriving as a 400",
      input: { status: 400, message: "RESOURCE_DOES_NOT_EXIST: Endpoint 'claude-sonnet' does not exist." },
      expected: "model-not-found",
    },
    {
      name: "OpenAI-shaped unknown model",
      input: { status: 400, message: "The model `gpt-5.9` does not exist or you do not have access" },
      expected: "model-not-found",
    },

    // --- policy -----------------------------------------------------------------------------
    {
      name: "content filter beats the 400 status",
      input: { status: 400, message: "The response was filtered due to the prompt triggering the content filter" },
      expected: "policy",
    },
    {
      name: "policy beats 403, which would otherwise be auth",
      input: { status: 403, message: "Blocked by content management policy" },
      expected: "policy",
    },
    {
      name: "Responsible AI refusal (the V-12 outcome-D shape)",
      input: { status: 200, message: "Responsible AI Service refused the request" },
      expected: "policy",
    },

    // --- network ----------------------------------------------------------------------------
    { name: "500", input: { status: 500, message: "Internal Server Error" }, expected: "network" },
    { name: "503", input: { status: 503, message: "Service Unavailable" }, expected: "network" },
    { name: "408", input: { status: 408, message: "Request Timeout" }, expected: "network" },
    {
      name: "no response at all — the cause chain carries the code",
      input: {
        message: "fetch failed",
        cause: Object.assign(new Error("connect ECONNREFUSED 127.0.0.1:8888"), {
          code: "ECONNREFUSED",
        }),
      },
      expected: "network",
    },
    {
      name: "corporate TLS interception",
      input: { message: "unable to verify the first certificate" },
      expected: "network",
    },
    {
      name: "PI diagnostics carry the code when the message does not",
      input: {
        message: "request failed",
        diagnostics: [{ type: "stream", error: { message: "socket error", code: "ENOTFOUND" } }],
      },
      expected: "network",
    },
    {
      name: "last resort: an unclassifiable non-2xx is network, never a guessed auth/quota",
      input: { status: 418, message: "I'm a teapot" },
      expected: "network",
    },

    // --- status carried only by the text ------------------------------------------------------
    // Observed 2026-08-07: `databricks/databricks-claude-sonnet-4-5` behind a workspace IP ACL
    // threw before any response object existed, so `after_provider_response` never fired and the
    // only surviving trace of the 403 was the message text. It used to classify as `network`.
    {
      name: "403 recovered from the message when no status reached the hook",
      input: { message: "403 status code (no body)" },
      expected: "auth",
    },
    {
      name: "429 recovered from the message",
      input: { message: "Request failed with status code 429" },
      expected: "quota",
    },
    {
      name: "404 recovered from an HTTP-prefixed message",
      input: { message: "HTTP 404 while calling /serving-endpoints/claude" },
      expected: "model-not-found",
    },
    {
      name: "a recovered 5xx is still network",
      input: { message: "502 status code (no body)" },
      expected: "network",
    },
    {
      name: "policy still beats a recovered 403, exactly as it beats an observed one",
      input: { message: "403 status code: Blocked by content management policy" },
      expected: "policy",
    },
    {
      name: "a bare three-digit number is not a status",
      input: { message: "connect ECONNREFUSED 127.0.0.1:8888 after 403 ms" },
      expected: "network",
    },
  ];

  for (const { name, input, expected } of table) {
    it(`${name} -> ${expected}`, () => {
      assert.equal(classifyProviderError(input), expected);
    });
  }

  it("searches the whole cause chain, not just the outermost message", () => {
    const inner = Object.assign(new Error("getaddrinfo EAI_AGAIN copilot-api.example"), {
      code: "EAI_AGAIN",
    });
    const outer = new Error("fetch failed", { cause: inner });
    assert.equal(classifyProviderError({ message: "provider call failed", cause: outer }), "network");
  });
});

describe("formatProviderFailure — every field routing.json asks to report", () => {
  const failure = buildProviderFailure({
    provider: "github-copilot",
    model: "claude-opus-5",
    status: 401,
    message: "Bad credentials: the gho_ token was rejected by copilot-api",
    cause: new Error("HTTP 401", { cause: new Error("token rotated 2026-08-01") }),
  });

  it("names provider, model, class and message", () => {
    const text = formatProviderFailure(failure);
    assert.match(text, /provider : github-copilot/);
    assert.match(text, /model {4}: claude-opus-5/);
    assert.match(text, /class {4}: auth/);
    assert.match(text, /message {2}: Bad credentials: the gho_ token was rejected by copilot-api/);
  });

  it("preserves the cause chain rather than flattening it", () => {
    const text = formatProviderFailure(failure);
    assert.match(text, /cause {4}: Error: HTTP 401 <- caused by Error: token rotated 2026-08-01/);
  });

  it("states the abort policy, so no reader assumes a fallback was tried", () => {
    assert.match(formatProviderFailure(failure), /no failover, no substitution, no retry/);
  });

  it("does not truncate a long upstream message", () => {
    const long = "x".repeat(9_000);
    const text = formatProviderFailure(
      buildProviderFailure({ provider: "openai", model: "gpt-5.5", status: 500, message: long }),
    );
    assert.ok(text.includes(long), "the upstream message must survive whole");
  });

  it("renders PI diagnostics including the stack, which is the only surviving chain", () => {
    const lines = formatDiagnostics([
      {
        type: "stream_error",
        error: {
          name: "TypeError",
          code: "UND_ERR_SOCKET",
          message: "other side closed",
          stack: "TypeError: other side closed\n    at Socket.onclose (node:internal/x:1:1)",
        },
        details: { attempt: 1 },
      },
    ]);
    assert.match(lines[0] ?? "", /stream_error — TypeError\[UND_ERR_SOCKET\]: other side closed/);
    assert.ok(lines.some((l) => l.includes("at Socket.onclose")), "the stack must be rendered");
    assert.ok(lines.some((l) => l.includes('details: {"attempt":1}')));
  });
});

describe("a status that only the message carried", () => {
  // The regression this block exists for. Live run, 2026-08-07:
  //
  //   pi -p '...' --model databricks/databricks-claude-sonnet-4-5
  //   class    : network
  //   http     : (no response — the request never reached the provider)
  //   message  : 403 status code (no body)
  //
  // The `http` line contradicted the `message` line directly below it, and it was the `http` line
  // that was wrong: curling the endpoint by hand returned an Azure Databricks workspace IP ACL
  // rejection. A reader trusting the block would have gone looking at DNS and the proxy.
  const failure = buildProviderFailure({
    provider: "databricks",
    model: "databricks-claude-sonnet-4-5",
    message: "403 status code (no body)",
  });

  it("reports the status it classified on, instead of claiming no response arrived", () => {
    const text = formatProviderFailure(failure);
    assert.equal(failure.status, 403);
    assert.equal(failure.klass, "auth");
    assert.match(text, /http {5}: 403/);
    assert.doesNotMatch(text, /never reached the provider/);
    assert.match(summariseProviderFailure(failure), /— auth \(http 403\)$/);
  });

  it("still says so plainly when there is genuinely no status anywhere", () => {
    const text = formatProviderFailure(
      buildProviderFailure({
        provider: "openai",
        model: "gpt-5.5",
        message: "TypeError: fetch failed",
      }),
    );
    assert.match(text, /http {5}: \(no status — none on the wire, none in the upstream text\)/);
  });
});

describe("the mid-stream 200 — the path after_provider_response cannot see", () => {
  const failure = buildProviderFailure({
    provider: "databricks",
    model: "databricks-claude-sonnet-4-5",
    status: 200,
    midStream: true,
    message: "stream terminated unexpectedly after 412 tokens",
  });

  it("never reports a bare 'http 200' for a failed turn", () => {
    const text = formatProviderFailure(failure);
    assert.match(text, /headers ok; the stream failed after them/);
    assert.doesNotMatch(summariseProviderFailure(failure), /^.*http 200\)$/);
  });

  it("still classifies, from the message text alone", () => {
    assert.equal(failure.klass, "network");
  });
});

describe("the empty 200 — a well-formed response that carried no completion", () => {
  // The live failure, 2026-08-14, against an OpenAI-compatible LiteLLM gateway serving
  // `gpt-5.6-luna`. Nine subagent runs died with "Subagent produced no output (possible model
  // cold-start or empty response)" while the transcripts recorded this, verbatim, as the run's
  // last assistant message:
  //
  //   .pi-subagents/artifacts/<runId>_<agent>_transcript.jsonl
  //
  // Reproduced against a stub gateway that answers 200 with a stream carrying a role delta, a
  // `finish_reason: "stop"` delta and nothing else: PI hands up exactly this message, `pi -p
  // --mode json` exits 0, and every guard in the stack reads it as "the model had nothing to
  // say". A 400 from the same stub is NOT this shape — it arrives as `stopReason: "error"` with
  // the upstream body in `errorMessage` — which is what rules the gateway's `reasoning_effort`
  // vocabulary out as the cause, and what this fixture pins.
  const recorded = {
    role: "assistant",
    content: [] as { type: string }[],
    api: "openai-completions",
    provider: "openai",
    model: "gpt-5.6-luna",
    usage: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
    stopReason: "stop",
    rawStopReason: "stop",
    responseId: "chatcmpl-2e6c1517-8984-4434-9673-a0fb231c5e3f",
  };

  it("recognises the recorded failure", () => {
    assert.equal(isEmptyCompletion(recorded), true);
  });

  it("does not fire on the healthy turn from the same transcript — a tool call is content", () => {
    // Turn 1 of the same run: `stopReason: "toolUse"`, 83 output tokens of which 43 reasoning,
    // and a `read` call that executed. A run that gets this far has reached the model.
    assert.equal(
      isEmptyCompletion({
        content: [{ type: "toolCall" }],
        stopReason: "toolUse",
        usage: { input: 5101, output: 83 },
      }),
      false,
    );
  });

  it("does not fire on a thinking-only turn — a reasoning block is content too", () => {
    assert.equal(isEmptyCompletion({ content: [{ type: "thinking" }], stopReason: "stop" }), false);
  });

  it("does not fire on text", () => {
    assert.equal(isEmptyCompletion({ content: [{ type: "text" }], stopReason: "stop" }), false);
  });

  it("leaves the states where empty content is legitimate alone", () => {
    // `error` belongs to the branch above it, `aborted` is Esc, `pending` has not finished, and
    // `deferred` is a batch handle whose content arrives later by design.
    for (const stopReason of ["error", "aborted", "pending", "deferred"]) {
      assert.equal(isEmptyCompletion({ content: [], stopReason }), false, stopReason);
    }
  });

  it("fires on a length stop with no content — a turn that spent its budget on nothing", () => {
    assert.equal(isEmptyCompletion({ content: [], stopReason: "length" }), true);
  });

  it("cannot be tricked by a message with no content array at all", () => {
    assert.equal(isEmptyCompletion({ stopReason: "stop" }), false);
  });

  it("reports the observation, never a guessed cause", () => {
    const failure = buildEmptyCompletionFailure({
      provider: "openai",
      model: "gpt-5.6-luna",
      status: 200,
      stopReason: recorded.stopReason,
      rawStopReason: recorded.rawStopReason,
      responseId: recorded.responseId,
      thinkingLevel: "high",
      usage: recorded.usage,
    });
    const text = formatProviderFailure(failure);
    assert.equal(failure.klass, "empty-response");
    assert.match(text, /provider : openai/);
    assert.match(text, /model {4}: gpt-5\.6-luna/);
    assert.match(text, /0 content parts/);
    assert.match(text, /finish_reason=stop/);
    // The run's metadata said `openai/gpt-5.6-luna:max`; the level that reached the wire was
    // `high`. Printing it is what makes that visible without a live probe.
    assert.match(text, /reasoning effort=high/);
    assert.match(text, /responseId=chatcmpl-2e6c1517-8984-4434-9673-a0fb231c5e3f/);
    assert.match(text, /usage 0 prompt \/ 0 completion token\(s\)/);
    assert.match(text, /not evidence/);
    // These claims were refuted by a live probe on 2026-08-14 — zero prompt tokens is what
    // `pi-ai` pre-initialises usage to, not a measurement, and it does not mean the request was
    // never billed or never reached the model behind the gateway. None of them may reappear.
    assert.doesNotMatch(text, /did not reach/i);
    assert.doesNotMatch(text, /billed/i);
    assert.doesNotMatch(text, /never reached/i);
    // The string this whole investigation was lost to. It must never come back.
    assert.doesNotMatch(text, /cold[- ]start/i);
  });

  it("never reports a bare http 200 for a turn that produced nothing", () => {
    const failure = buildEmptyCompletionFailure({
      provider: "openai",
      model: "gpt-5.6-luna",
      status: 200,
      stopReason: "stop",
    });
    assert.match(formatProviderFailure(failure), /200 \(a complete, well-formed response whose body/);
    assert.match(summariseProviderFailure(failure), /empty-response \(http 200, empty body\)$/);
  });

  it("says so plainly when no status reached the hook", () => {
    const failure = buildEmptyCompletionFailure({ provider: "openai", model: "gpt-5.6-luna", stopReason: "stop" });
    assert.match(summariseProviderFailure(failure), /\(http 2xx, empty body\)$/);
  });

  it("is not reachable from the text classifier — it is a shape, not a message", () => {
    assert.notEqual(classifyProviderError({ message: "the provider returned an empty completion" }), "empty-response");
    assert.notEqual(classifyProviderError({ status: 200, message: "" }), "empty-response");
  });
});

describe("pickGatewayHeaders — the correlation-header allow-list", () => {
  it("keeps only the four named headers, lower-cased, in fixed order", () => {
    const picked = pickGatewayHeaders({
      "X-LiteLLM-Call-Id": "abc123",
      "x-litellm-version": "1.89.7",
      "x-litellm-key-hash": "should-never-appear",
      "content-type": "application/json",
    });
    assert.deepEqual(picked, [
      ["x-litellm-call-id", "abc123"],
      ["x-litellm-version", "1.89.7"],
    ]);
  });

  it("returns undefined, not an empty array, when nothing matched", () => {
    assert.equal(pickGatewayHeaders({ "content-type": "application/json" }), undefined);
    assert.equal(pickGatewayHeaders(undefined), undefined);
  });

  it("never lets a key/spend header through, even by prefix", () => {
    const picked = pickGatewayHeaders({ "x-litellm-key-spend": "42.10" });
    assert.equal(picked, undefined);
  });

  it("formatProviderFailure renders the gateway line only when headers were captured", () => {
    const withHeaders = buildEmptyCompletionFailure({
      provider: "openai",
      model: "gpt-5.6-luna",
      status: 200,
      stopReason: "stop",
      headers: { "x-litellm-call-id": "req-42" },
    });
    assert.match(formatProviderFailure(withHeaders), /gateway {2}: x-litellm-call-id=req-42/);

    const without = buildEmptyCompletionFailure({
      provider: "openai",
      model: "gpt-5.6-luna",
      status: 200,
      stopReason: "stop",
    });
    assert.doesNotMatch(formatProviderFailure(without), /gateway {2}:/);
  });
});

describe("PROVIDER_FAILURE_MARKER", () => {
  it("is the exact prefix summariseProviderFailure emits — the two must never drift apart", () => {
    const failure = buildProviderFailure({ provider: "openai", model: "gpt-5.6-luna", message: "boom" });
    assert.ok(summariseProviderFailure(failure).startsWith(PROVIDER_FAILURE_MARKER));
  });
});

describe("surfaceProviderFailure", () => {
  it("writes the whole block to the log sink and never throws", () => {
    const lines: string[] = [];
    surfaceProviderFailure(
      undefined,
      buildProviderFailure({ provider: "local", model: "qwen", status: 503, message: "down" }),
      { log: (line) => lines.push(line) },
    );
    assert.equal(lines.length, 1);
    assert.match(lines[0] ?? "", /provider : local/);
  });

  it("survives a log sink that throws — an error reporter must not become the error", () => {
    assert.doesNotThrow(() =>
      surfaceProviderFailure(
        undefined,
        buildProviderFailure({ provider: "local", model: "qwen", message: "x" }),
        {
          log: () => {
            throw new Error("stderr is closed");
          },
        },
      ),
    );
  });

  it("survives a ui.notify that throws", () => {
    const ctx = {
      hasUI: true,
      ui: {
        notify: () => {
          throw new Error("TUI already torn down");
        },
      },
    } as unknown as Parameters<typeof surfaceProviderFailure>[0];
    assert.doesNotThrow(() =>
      surfaceProviderFailure(
        ctx,
        buildProviderFailure({ provider: "local", model: "qwen", message: "x" }),
        { log: () => {} },
      ),
    );
  });

  it("fails the process in headless mode — a script must not see exit 0 on a dead provider", () => {
    // The third rule. PI covers `pi -p` natively but the branch that
    // does it (`dist/modes/print-mode.js`) is gated on `mode === "text"`, so `--mode json` would
    // otherwise return 0 on a turn that never reached a model. `ctx.hasUI` is false in both.
    const codes: number[] = [];
    surfaceProviderFailure(
      { hasUI: false, ui: { notify: () => {} } } as unknown as Parameters<
        typeof surfaceProviderFailure
      >[0],
      buildProviderFailure({ provider: "databricks", model: "sonnet", status: 401, message: "no" }),
      { log: () => {}, setExitCode: (code) => codes.push(code) },
    );
    assert.deepEqual(codes, [1]);
  });

  it("leaves the exit code alone in interactive mode", () => {
    // One failed turn in a long session must not decide the exit status of a normal quit.
    const codes: number[] = [];
    surfaceProviderFailure(
      { hasUI: true, ui: { notify: () => {} } } as unknown as Parameters<
        typeof surfaceProviderFailure
      >[0],
      buildProviderFailure({ provider: "databricks", model: "sonnet", status: 401, message: "no" }),
      { log: () => {}, setExitCode: (code) => codes.push(code) },
    );
    assert.deepEqual(codes, []);
  });

  it("survives an exit-code sink that throws", () => {
    assert.doesNotThrow(() =>
      surfaceProviderFailure(
        { hasUI: false, ui: { notify: () => {} } } as unknown as Parameters<
          typeof surfaceProviderFailure
        >[0],
        buildProviderFailure({ provider: "local", model: "qwen", message: "x" }),
        {
          log: () => {},
          setExitCode: () => {
            throw new Error("frozen process object");
          },
        },
      ),
    );
  });
});

describe("the shipped routing table — the no-substitution contract this module implements", () => {
  const routing = JSON.parse(readFileSync(ROUTING_PATH, "utf8")) as {
    onProviderError?: {
      policy?: string;
      substituteProvider?: boolean;
      report?: string[];
      errorClasses?: string[];
    };
    tiers?: Record<string, { optional?: boolean }>;
    tiersUnbound?: Record<string, string>;
  };

  it("aborts and never substitutes a provider", () => {
    assert.equal(routing.onProviderError?.policy, "abort");
    assert.equal(routing.onProviderError?.substituteProvider, false);
  });

  it("reports exactly the fields formatProviderFailure emits", () => {
    assert.deepEqual(routing.onProviderError?.report, [
      "provider",
      "model",
      "errorClass",
      "message",
      "causeChain",
    ]);
  });

  it("declares the six classes this module can produce, and no others", () => {
    const declared = [...(routing.onProviderError?.errorClasses ?? [])].sort();
    assert.deepEqual(declared, [
      "auth",
      "empty-response",
      "model-not-found",
      "network",
      "policy",
      "quota",
    ]);
  });

  it("never makes the local tier a hard requirement — someone with no local model server must still start", () => {
    // The shipped table binds no local provider at all, so `local` lives in `tiersUnbound` with the
    // reason and the remedy. An install that does bind it must mark it optional instead: either way
    // a missing llama-swap is not a failed start.
    const bound = routing.tiers?.["local"];
    if (bound) {
      assert.equal(bound.optional, true, "a bound local tier must be optional");
    } else {
      assert.match(
        routing.tiersUnbound?.["local"] ?? "",
        /install/i,
        "an unbound local tier must explain how to bind it, not just be missing",
      );
    }
  });
});
