import { shippedConfig } from "../lib/repo-config.ts";
import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import {
  DEFAULT_DISPATCH_CONFIG,
  configPaths,
  expandDir,
  loadConfiguredProviders,
  loadDispatchSettings,
  registryDirs,
} from "../../extensions/dispatch/config.ts";
import { scratch } from "./helpers.ts";
import { CONFIG_DIR as REPO_CONFIG } from "../lib/repo-config.ts";

const write = (dir: string, name: string, value: unknown): string => {
  const path = join(dir, name);
  writeFileSync(path, typeof value === "string" ? value : JSON.stringify(value), "utf8");
  return path;
};

const MINIMAL_ROUTING = {
  tiers: { fast: { model: "github-copilot/gpt-5.1" } },
  egress: { "github-copilot": "public" },
};

/**
 * `config/routing.json` and `config/guard.json` are generated by `scripts/install.sh` from tracked
 * `*.default.json` templates and are git-ignored, so a clean checkout has only the templates.
 * `shippedConfig()` resolves to whichever exists — see test/lib/repo-config.ts — and the assertions
 * below have to hold for both, because the installer produces one from the other.
 */
const SHIPPED_ROUTING = shippedConfig("routing");
const SHIPPED_MODELS = shippedConfig("models");

describe("the repo's own config files", () => {
  it("loads config/dispatch.json and the shipped routing table clean", () => {
    const settings = loadDispatchSettings({ routingPath: SHIPPED_ROUTING, modelsPath: SHIPPED_MODELS });
    assert.deepEqual(settings.problems, [], `problems: ${settings.problems.join(" | ")}`);
    assert.match(settings.sources.dispatch, /config\/dispatch\.json$/);
    assert.match(settings.sources.routing, /config\/routing(\.default)?\.json$/);
    assert.notEqual(settings.routing, undefined);
  });

  it("the routing table is the single source of truth for every tier this item resolves", () => {
    const { routing, dispatch } = loadDispatchSettings({ routingPath: SHIPPED_ROUTING });
    assert.ok(routing);
    // A tier is either BOUND to a model whose provider has an egress class, or explicitly UNBOUND
    // with a reason. The shipped template binds strong/light to public GitHub Copilot and leaves
    // confidential unbound, because no public default can assume an endpoint inside the operator's
    // boundary exists; an install binds whatever the operator selected. Silence — a tier that is
    // neither bound nor explained — is the failure, because that is what turns into "unknown tier".
    //
    // The list below IS the tier vocabulary, not a sample of it. Owner decision, 2026-08-15: three
    // tiers, `strong`, `light` and `confidential`. `light` carries the role the former `cheap` tier
    // had; `fast` and `local` were deleted outright. Adding a tier to `routing.default.json` without
    // adding it here would leave it untested, so this loop is also the vocabulary's own gate.
    for (const tier of ["strong", "light", "confidential"]) {
      const bound = routing.tiers[tier];
      if (bound) {
        const provider = bound.model.split("/")[0]!;
        assert.ok(routing.egress[provider], `provider "${provider}" of tier "${tier}" needs an egress class`);
        assert.ok(!routing.unboundTiers?.[tier], `tier "${tier}" is both bound and listed as unbound`);
      } else {
        assert.ok(
          routing.unboundTiers?.[tier],
          `tier "${tier}" is neither bound in "tiers" nor explained in "tiersUnbound"`,
        );
      }
    }
    assert.ok(routing.tiers[dispatch.defaultTier], "the configured default tier must be bound");
  });

  it("a provider's concurrency cap comes from its own fragment, and the shipped table agrees", () => {
    // The cap used to be asserted against `routing.json`'s concurrency map, which only exists once an
    // install has selected the provider. The fact itself lives in the fragment the installer copies
    // it from, so that is where it is pinned. This used to name `local.json` and its cap of 1 — a
    // model server on one machine's GPU being one request at a time. That fragment was deleted with
    // the lane (owner decision, 2026-08-15), so the assertion is now the general invariant it was
    // always a special case of, over whichever fragments ship.
    const fragments = readdirSync(join(REPO_CONFIG, "providers"))
      .filter((f) => f.endsWith(".json"))
      .map((f) => [f.replace(/\.json$/, ""), JSON.parse(readFileSync(join(REPO_CONFIG, "providers", f), "utf8"))]) as [
      string,
      { concurrency?: number | string },
    ][];
    assert.ok(fragments.length > 0, "at least one provider fragment must ship");

    const { routing } = loadDispatchSettings({ routingPath: SHIPPED_ROUTING });
    for (const [name, fragment] of fragments) {
      // A `{{mustache}}` cap is one the operator answers at install time — there is no fixed number
      // to pin, and pinning the placeholder would assert the template, not the contract.
      if (typeof fragment.concurrency === "string") {
        assert.match(fragment.concurrency, /^\{\{[a-zA-Z]+\}\}$/, `${name}: an unresolved cap must be a placeholder`);
        continue;
      }
      assert.ok(
        Number.isInteger(fragment.concurrency) && (fragment.concurrency as number) >= 1,
        `${name}: concurrency must be a positive integer, got ${String(fragment.concurrency)}`,
      );
      const shipped = routing?.concurrency[name];
      if (shipped !== undefined) assert.equal(shipped, fragment.concurrency, `${name}: table disagrees with fragment`);
    }
  });

  it("dispatch.json's dispatchTools cover the guard's dispatch tool list", () => {
    const { dispatch } = loadDispatchSettings({ routingPath: SHIPPED_ROUTING });
    const guard = JSON.parse(readFileSync(shippedConfig("guard"), "utf8")) as { dispatchTools?: string[] };
    for (const tool of guard.dispatchTools ?? []) {
      assert.ok(
        dispatch.dispatchTools.includes(tool),
        `the guard policy lists "${tool}" as a dispatch tool; dispatch.json must too, or this extension ` +
          `neither refuses it at depth nor strips it from the child ceiling`,
      );
    }
  });
});

describe("loadDispatchSettings", () => {
  it("uses built-in defaults, loudly, when dispatch.json is absent", () => {
    const dir = scratch();
    const settings = loadDispatchSettings({
      dispatchPath: join(dir, "nope.json"),
      routingPath: write(dir, "routing.json", MINIMAL_ROUTING),
    });
    assert.equal(settings.dispatch.maxDepth, DEFAULT_DISPATCH_CONFIG.maxDepth);
    assert.match(settings.problems.join("\n"), /built-in dispatch defaults are in force/);
    assert.notEqual(settings.routing, undefined, "a missing dispatch.json must not disable dispatch");
  });

  it("REFUSES dispatch when routing.json is absent - there is no safe default for a tier", () => {
    const dir = scratch();
    const settings = loadDispatchSettings({
      dispatchPath: write(dir, "dispatch.json", {}),
      routingPath: join(dir, "nope.json"),
    });
    assert.equal(settings.routing, undefined);
    assert.match(settings.problems.join("\n"), /DISPATCH IS REFUSED until routing\.json is readable/);
  });

  it("treats a pinned-but-missing path as a typo, not as a hint to look elsewhere", () => {
    const dir = scratch();
    const settings = loadDispatchSettings({
      dispatchPath: write(dir, "dispatch.json", {}),
      routingPath: join(dir, "typo.json"),
    });
    assert.equal(settings.routing, undefined, "it must NOT silently fall back to the repo's routing.json");
    assert.match(settings.problems.join("\n"), /was pinned to ".*typo\.json", which does not exist/);
  });

  it("REFUSES dispatch when routing.json has no tiers or no egress map", () => {
    const dir = scratch();
    const noTiers = loadDispatchSettings({
      dispatchPath: write(dir, "dispatch.json", {}),
      routingPath: write(dir, "r1.json", { egress: {} }),
    });
    assert.equal(noTiers.routing, undefined);
    assert.match(noTiers.problems.join("\n"), /"tiers" is missing/);

    const noEgress = loadDispatchSettings({
      dispatchPath: write(dir, "dispatch.json", {}),
      routingPath: write(dir, "r2.json", { tiers: MINIMAL_ROUTING.tiers }),
    });
    assert.equal(noEgress.routing, undefined);
    assert.match(noEgress.problems.join("\n"), /"egress" is missing/);
  });

  it("REFUSES dispatch on malformed JSON rather than falling back", () => {
    const dir = scratch();
    const settings = loadDispatchSettings({
      dispatchPath: write(dir, "dispatch.json", {}),
      routingPath: write(dir, "routing.json", "{ not json"),
    });
    assert.equal(settings.routing, undefined);
    assert.match(settings.problems.join("\n"), /is not valid JSON/);
  });

  it("drops an individual bad tier by name and keeps the rest", () => {
    const dir = scratch();
    const settings = loadDispatchSettings({
      dispatchPath: write(dir, "dispatch.json", {}),
      routingPath: write(dir, "routing.json", {
        tiers: { fast: { model: "github-copilot/gpt-5.1" }, broken: { model: "no-provider" } },
        egress: { "github-copilot": "public" },
      }),
    });
    assert.deepEqual(Object.keys(settings.routing?.tiers ?? {}), ["fast"]);
    assert.match(settings.problems.join("\n"), /tier "broken" needs a "model" of the form provider\/id/);
  });

  it("rejects a fallback chain in routing.json - EXT-08 is cancelled", () => {
    const dir = scratch();
    const settings = loadDispatchSettings({
      dispatchPath: write(dir, "dispatch.json", {}),
      routingPath: write(dir, "routing.json", { ...MINIMAL_ROUTING, fallback: ["cheap", "local"] }),
    });
    assert.match(settings.problems.join("\n"), /Provider failover is cancelled \(EXT-08\); remove it/);
  });

  it("names each bad dispatch.json field and keeps the default for it", () => {
    const dir = scratch();
    const settings = loadDispatchSettings({
      dispatchPath: write(dir, "dispatch.json", {
        maxDepth: "two",
        defaultEgress: "secret",
        concurrencyDefault: 0,
        dispatchTools: ["subagent", 7],
      }),
      routingPath: write(dir, "routing.json", MINIMAL_ROUTING),
    });
    const text = settings.problems.join("\n");
    assert.match(text, /"maxDepth" must be a number/);
    assert.match(text, /"defaultEgress" must be one of/);
    assert.match(text, /"concurrencyDefault" must be a number/);
    assert.match(text, /"dispatchTools" must be an array of non-empty strings/);
    assert.equal(settings.dispatch.maxDepth, DEFAULT_DISPATCH_CONFIG.maxDepth);
    assert.equal(settings.dispatch.defaultEgress, DEFAULT_DISPATCH_CONFIG.defaultEgress);
    assert.deepEqual(settings.dispatch.dispatchTools, DEFAULT_DISPATCH_CONFIG.dispatchTools);
  });

  it("reads onThinkingClamp, and keeps warning-and-proceeding when it is misspelled", () => {
    const dir = scratch();
    const abort = loadDispatchSettings({
      dispatchPath: write(dir, "dispatch.json", { onThinkingClamp: "abort" }),
      routingPath: write(dir, "routing.json", MINIMAL_ROUTING),
    });
    assert.equal(abort.dispatch.onThinkingClamp, "abort");
    const typo = loadDispatchSettings({
      dispatchPath: write(dir, "dispatch2.json", { onThinkingClamp: "Abort" }),
      routingPath: write(dir, "routing.json", MINIMAL_ROUTING),
    });
    assert.match(typo.problems.join("\n"), /"onThinkingClamp" must be "warn" or "abort"/);
    assert.equal(typo.dispatch.onThinkingClamp, "warn", "a typo must not silently refuse every dispatch");
  });

  it("lets a routing.json dispatch block win over dispatch.json, so the shared file is authoritative", () => {
    const dir = scratch();
    const settings = loadDispatchSettings({
      dispatchPath: write(dir, "dispatch.json", { maxDepth: 2, defaultTier: "fast" }),
      routingPath: write(dir, "routing.json", { ...MINIMAL_ROUTING, dispatch: { maxDepth: 1 } }),
    });
    assert.equal(settings.dispatch.maxDepth, 1);
    assert.equal(settings.dispatch.defaultTier, "fast", "keys the overlay omits are kept");
  });
});

describe("registry directories", () => {
  it("expands the <repo>, <agentDir> and <cwd> tokens to absolute paths", () => {
    const cwd = scratch();
    assert.equal(expandDir("<cwd>/.pi/agents", cwd), join(cwd, ".pi/agents"));
    for (const token of ["<repo>/agents", "<agentDir>/agents"]) {
      const expanded = expandDir(token, cwd);
      assert.ok(expanded.startsWith("/"), `${token} -> ${expanded} must be absolute`);
      assert.ok(!expanded.includes("<"), `${token} left an unexpanded token: ${expanded}`);
    }
  });

  it("de-duplicates while preserving override order", () => {
    const cwd = scratch();
    const dirs = registryDirs(
      { ...DEFAULT_DISPATCH_CONFIG, registryDirs: ["<cwd>/agents", "<cwd>/agents", "<cwd>/.pi/agents"] },
      cwd,
    );
    assert.deepEqual(dirs, [join(cwd, "agents"), join(cwd, ".pi/agents")]);
  });
});

describe("configPaths", () => {
  it("puts an explicit override first and always offers the repo's own config dir", () => {
    const paths = configPaths("dispatch.json", "/somewhere/else.json");
    assert.equal(paths[0], "/somewhere/else.json");
    assert.ok(paths.some((p) => p.endsWith("/config/dispatch.json")));
  });
});

describe("loadConfiguredProviders", () => {
  it("reads the repo's own shipped provider list, and nothing PI merely knows about", () => {
    // `config/models.json` is generated and git-ignored; on a clean checkout `shippedConfig()`
    // falls back to `config/models.default.json`, which declares only `github-copilot`. Either way
    // the set must be exactly the providers file's own keys — never a provider PI's own registry
    // happens to know a client for.
    const providers = loadConfiguredProviders(shippedConfig("models"));
    assert.ok(providers);
    const raw = JSON.parse(readFileSync(shippedConfig("models"), "utf8")) as { providers?: Record<string, unknown> };
    assert.deepEqual([...providers!].sort(), Object.keys(raw.providers ?? {}).sort());
    assert.ok(!providers!.has("deepseek"), "the provider nobody configured: known to PI, declared by nobody");
  });

  it("returns the keys of an override file, ignoring everything else in it", () => {
    const dir = scratch("ext05-models-");
    const path = write(dir, "models.json", { _costNote: "x", providers: { litellm: { baseUrl: "https://x" } } });
    assert.deepEqual([...loadConfiguredProviders(path)!], ["litellm"]);
  });

  it("is undefined — 'cannot say' — when the file is absent or has no providers block", () => {
    const dir = scratch("ext05-models-");
    assert.equal(loadConfiguredProviders(join(dir, "nope.json")), undefined);
    assert.equal(loadConfiguredProviders(write(dir, "models.json", { providers: [] })), undefined);
    assert.equal(loadConfiguredProviders(write(dir, "empty.json", {})), undefined);
  });

  it("says so in problems when the list could not be read, rather than filtering at half strength silently", () => {
    const dir = scratch("ext05-models-");
    const settings = loadDispatchSettings({
      routingPath: write(dir, "routing.json", MINIMAL_ROUTING),
      modelsPath: join(dir, "absent-models.json"),
    });
    assert.equal(settings.configuredProviders, undefined);
    assert.ok(settings.problems.some((p) => p.includes("models.json could not be read")));
  });
});
