/**
 * End-to-end through the registered `teammate` tool, with a scripted child.
 *
 * The child here delivers by calling the *injected* `reply_to_lead` tool, so this exercises the real
 * path — runtime appends the contract, runtime injects the tool, child calls it, obligation closes —
 * rather than reaching into the registry the way the unit tests do.
 */
import { readShippedConfig, shippedConfig } from "../lib/repo-config.ts";
import assert from "node:assert/strict";
import { copyFile, mkdir, mkdtemp, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { before, describe, it } from "node:test";
import type {
  ExtensionAPI,
  ExtensionContext,
  ToolDefinition,
} from "@earendil-works/pi-coding-agent";

import { DELIVERY_CONTRACT, MAX_TEAMMATES, REPLY_TOOL } from "../../extensions/teammates/contract.ts";
import { register } from "../../extensions/teammates/index.ts";
import type { SpawnRequest, TeammateSpawner } from "../../extensions/teammates/runtime.ts";
import { resetSurfaced } from "../../extensions/lib/once.ts";
import { FakeSession, type Deliver, type Turn } from "./fake.ts";

type Handler = (event: unknown, ctx: ExtensionContext) => Promise<void> | void;

interface SentMessage {
  customType: string;
  text: string;
}

interface Harness {
  tool: ToolDefinition;
  handlers: Map<string, Handler>;
  sent: SentMessage[];
  spawned: Array<{ req: SpawnRequest; session: FakeSession }>;
  ctx: ExtensionContext;
  notices: string[];
  start(): Promise<void>;
}

const AGENT_FILE = [
  "---",
  "name: code-reviewer",
  "description: Reviews code changes for correctness and clarity.",
  "model: cheap",
  "---",
  "You review code. Return your findings as your final message.",
].join("\n");

let cwd: string;

/**
 * The model the shipped routing table binds the `cheap` tier to — the tier `AGENT_FILE` declares.
 * Read from the table rather than hardcoded: the registry validates an agent's resolved model
 * against what the session offers, so a fake registry that offers something else makes every spawn
 * fail for a reason that has nothing to do with the teammate runtime.
 *
 * Two forms, because they are two different things since 2026-08-13. The registry is keyed by bare
 * `provider/id`, so that is what a fake `getAvailable()` has to offer. What actually goes on the
 * wire is the RESOLVED id, which carries the tier's declared `thinkingLevel` as a `:<level>` suffix
 * — that suffix is the only channel PI reads a child's reasoning effort from, and a teammate is a
 * child like any other, so it must arrive there too.
 */
const CHEAP_TIER = readShippedConfig<{ tiers: Record<string, { model: string; thinkingLevel?: string }> }>("routing")
  .tiers["cheap"]!;

const CHEAP_MODEL = (() => {
  const [provider, ...rest] = CHEAP_TIER.model.split("/");
  return { provider: provider!, id: rest.join("/") };
})();

const CHEAP_MODEL_RESOLVED = {
  provider: CHEAP_MODEL.provider,
  id: CHEAP_TIER.thinkingLevel ? `${CHEAP_MODEL.id}:${CHEAP_TIER.thinkingLevel}` : CHEAP_MODEL.id,
};

before(async () => {
  const root = await mkdtemp(join(process.env.TMPDIR ?? tmpdir(), "pi-teammates-e2e-"));
  cwd = join(root, "repo");
  await mkdir(join(cwd, ".pi", "agents"), { recursive: true });
  await writeFile(join(cwd, ".pi", "agents", "code-reviewer.md"), AGENT_FILE, "utf8");
  // Keep every side effect (session index, scratch spill, agent discovery) inside the sandbox.
  process.env.XDG_STATE_HOME = join(root, "state");
  process.env.PI_CODING_AGENT_DIR = join(root, "agentdir");

  // A sandbox repo that looks INSTALLED. Dispatch refuses to resolve any agent's model or egress
  // without a readable `config/routing.json`, and that file is generated by scripts/install.sh, so no
  // clean checkout has one. This used to point at a directory with no config at all and passed only
  // because the loader then found the real checkout's generated copy — i.e. whatever the developer
  // running the suite happened to have installed. Seeding the tracked template makes the fixture say
  // what it always meant to say.
  const sandboxRepo = join(root, "repo-config");
  await mkdir(join(sandboxRepo, "config"), { recursive: true });
  await copyFile(shippedConfig("routing"), join(sandboxRepo, "config", "routing.json"));
  process.env.PI_CONFIG_REPO = sandboxRepo;
});

function harness(scripts: Record<string, Turn[]>): Harness {
  const handlers = new Map<string, Handler>();
  const tools = new Map<string, ToolDefinition>();
  const sent: SentMessage[] = [];
  const notices: string[] = [];
  const spawned: Array<{ req: SpawnRequest; session: FakeSession }> = [];

  const spawner: TeammateSpawner = async (req) => {
    const reply = req.customTools.find((t) => t.name === REPLY_TOOL);
    assert.ok(reply, "the runtime must inject reply_to_lead into every child");
    const deliver: Deliver = async (report, status) => {
      await reply.execute("child-call", { report, status }, undefined, undefined, {} as never);
    };
    const session = new FakeSession(req.name, deliver, scripts[req.name] ?? [{ act: "silent" }]);
    spawned.push({ req, session });
    return session;
  };

  const pi = {
    on: (event: string, handler: Handler) => void handlers.set(event, handler),
    registerTool: (tool: ToolDefinition) => void tools.set(tool.name, tool),
    registerCommand: () => {},
    appendEntry: () => {},
    sendMessage: (message: { customType: string; content: Array<{ text?: string }> }) => {
      sent.push({
        customType: message.customType,
        text: message.content.map((p) => p.text ?? "").join(""),
      });
    },
  } as unknown as ExtensionAPI;

  const ctx = {
    hasUI: false,
    cwd,
    mode: "print",
    ui: { notify: (line: string) => void notices.push(line), setStatus: () => {} },
    sessionManager: { getSessionId: () => "lead-session" },
    // Bare `provider/id`, because that is how the model registry is keyed — a resolved id's
    // `:<level>` suffix is stripped before existence is asked about.
    modelRegistry: { getAvailable: () => [CHEAP_MODEL] },
    // The lead runs on the same provider as the teammate it spawns, which is simply the realistic
    // arrangement. It used to matter more than that: until egress containment was withdrawn on
    // 2026-08-13, leaving this undefined dropped the session to the strictest default class and the
    // spawn was then refused for its provider's class rather than for anything under test here.
    model: CHEAP_MODEL,
  } as unknown as ExtensionContext;

  resetSurfaced();
  register(pi, { spawner });
  const tool = tools.get("teammate");
  assert.ok(tool, "the tool must be called `teammate`, not `dispatch_agent`");

  return {
    tool,
    handlers,
    sent,
    spawned,
    ctx,
    notices,
    start: async () => {
      await handlers.get("session_start")?.({}, ctx);
    },
  };
}

interface ToolResult {
  content: Array<{ type: string; text?: string }>;
  details: Record<string, unknown>;
}

async function call(h: Harness, params: Record<string, unknown>): Promise<ToolResult> {
  return (await h.tool.execute("call", params, undefined, undefined, h.ctx)) as unknown as ToolResult;
}

const textOf = (r: ToolResult): string => r.content.map((c) => c.text ?? "").join("");

describe("teammate tool", () => {
  it("spawns a named teammate and welds the delivery contract onto the child", async () => {
    const h = harness({});
    await h.start();
    const result = await call(h, { action: "spawn", name: "reviewer", agent: "code-reviewer" });

    assert.equal(h.spawned.length, 1);
    const req = h.spawned[0]!.req;
    assert.equal(req.systemPromptAppend[req.systemPromptAppend.length - 1], DELIVERY_CONTRACT);
    assert.match(req.systemPromptAppend[0]!, /You review code/);
    assert.deepEqual(req.model, CHEAP_MODEL_RESOLVED, "the tier's declared reasoning effort rides along");
    assert.match(textOf(result), /is live/);
    assert.match(textOf(result), new RegExp(`only ${REPLY_TOOL} delivers its work`));
  });

  it("delivers a report through the injected tool and returns it to the lead", async () => {
    const h = harness({ reviewer: [{ act: "deliver", report: "two findings in src/a.ts" }] });
    await h.start();
    await call(h, { action: "spawn", name: "reviewer", agent: "code-reviewer" });
    const result = await call(h, { action: "send", name: "reviewer", message: "review src/a.ts" });

    assert.equal(textOf(result), "two findings in src/a.ts");
    assert.equal(result.details.status, "complete");
    assert.equal(result.details.reminders, 0);
  });

  it("THE REGRESSION: a teammate that never delivers throws, naming the transcript", async () => {
    const h = harness({ reviewer: [{ act: "silent" }, { act: "silent" }, { act: "silent" }] });
    await h.start();
    await call(h, { action: "spawn", name: "reviewer", agent: "code-reviewer" });

    await assert.rejects(call(h, { action: "send", name: "reviewer", message: "review" }), (err: unknown) => {
      const msg = (err as Error).message;
      assert.match(msg, /did not deliver/);
      assert.match(msg, /UNDELIVERED after 2 reminder\(s\)/);
      assert.match(msg, /\/tmp-fake\/reviewer\.jsonl/);
      assert.match(msg, /UNVERIFIED and not a delivery/);
      return true;
    });
    // 1 message + exactly 2 reminders reached the child.
    assert.equal(h.spawned[0]!.session.prompts.length, 3);
  });

  it("a blocked teammate is reported as blocked, not as a failure to deliver", async () => {
    const h = harness({
      reviewer: [{ act: "deliver", report: "src/a.ts does not exist", status: "blocked" }],
    });
    await h.start();
    await call(h, { action: "spawn", name: "reviewer", agent: "code-reviewer" });
    const result = await call(h, { action: "send", name: "reviewer", message: "review" });
    assert.match(textOf(result), /reports it is BLOCKED/);
    assert.equal(result.details.status, "blocked");
  });

  it("holds the cap and names who is already live", async () => {
    const h = harness({});
    await h.start();
    for (let i = 0; i < MAX_TEAMMATES; i += 1) {
      await call(h, { action: "spawn", name: `mate-${i}`, agent: "code-reviewer" });
    }
    await assert.rejects(
      call(h, { action: "spawn", name: "one-too-many", agent: "code-reviewer" }),
      /refused — 4 already live/,
    );
    assert.equal(h.spawned.length, MAX_TEAMMATES, "the refused spawn must not open a session");
  });

  it("refuses an unknown agent by name, before opening any session", async () => {
    const h = harness({});
    await h.start();
    await assert.rejects(
      call(h, { action: "spawn", name: "reviewer", agent: "no-such-agent" }),
      /no agent "no-such-agent"/,
    );
    assert.equal(h.spawned.length, 0);
  });

  it("requires the arguments each action actually needs", async () => {
    const h = harness({});
    await h.start();
    await assert.rejects(call(h, { action: "spawn", name: "r" }), /needs a non-empty "agent"/);
    await assert.rejects(call(h, { action: "send", name: "r" }), /needs a non-empty "message"/);
    await assert.rejects(call(h, { action: "close" }), /needs a non-empty "name"/);
  });

  it("list shows the team, with each teammate's transcript", async () => {
    const h = harness({ reviewer: [{ act: "deliver", report: "ok" }] });
    await h.start();
    await call(h, { action: "spawn", name: "reviewer", agent: "code-reviewer" });
    await call(h, { action: "send", name: "reviewer", message: "review" });
    const result = await call(h, { action: "list" });
    assert.match(textOf(result), /reviewer\s+code-reviewer\s+idle/);
    assert.match(textOf(result), /1 delivered, 0 undelivered/);
    assert.deepEqual(result.details.team, ["reviewer"]);
  });

  it("close disposes the child session and frees the name", async () => {
    const h = harness({});
    await h.start();
    await call(h, { action: "spawn", name: "reviewer", agent: "code-reviewer" });
    await call(h, { action: "close", name: "reviewer" });
    assert.equal(h.spawned[0]!.session.disposed, 1);
    await call(h, { action: "spawn", name: "reviewer", agent: "code-reviewer" });
    assert.equal(h.spawned.length, 2);
  });

  it("turn_end tells the lead about undelivered work, once, by name", async () => {
    const h = harness({ reviewer: [{ act: "silent" }, { act: "silent" }, { act: "silent" }] });
    await h.start();
    await call(h, { action: "spawn", name: "reviewer", agent: "code-reviewer" });
    await assert.rejects(call(h, { action: "send", name: "reviewer", message: "review" }));

    await h.handlers.get("turn_end")?.({}, h.ctx);
    await h.handlers.get("turn_end")?.({}, h.ctx);
    // The send path already announced it; the notice must not repeat every turn afterwards.
    assert.equal(h.sent.filter((m) => m.customType === "teammate-undelivered").length, 0);
  });

  it("turn_end announces a teammate stranded without a failed send", async () => {
    const h = harness({});
    await h.start();
    await call(h, { action: "spawn", name: "reviewer", agent: "code-reviewer" });

    // Hold the child inside its first turn so the exchange is genuinely open when turn_end fires.
    const session = h.spawned[0]!.session;
    let release = (): void => {};
    const gate = new Promise<void>((resolve) => {
      release = resolve;
    });
    const original = session.prompt.bind(session);
    session.prompt = async (text: string) => {
      await gate;
      await original(text);
    };

    const promise = call(h, { action: "send", name: "reviewer", message: "review" });
    await Promise.resolve();
    await h.handlers.get("turn_end")?.({}, h.ctx);

    const notices = h.sent.filter((m) => m.customType === "teammate-undelivered");
    assert.equal(notices.length, 1);
    assert.match(notices[0]!.text, /reviewer/);
    assert.match(notices[0]!.text, /still working/);

    release();
    await assert.rejects(promise);
  });

  it("session_shutdown disposes every child and reports what never arrived", async () => {
    const h = harness({ reviewer: [{ act: "silent" }, { act: "silent" }, { act: "silent" }] });
    await h.start();
    await call(h, { action: "spawn", name: "reviewer", agent: "code-reviewer" });
    await call(h, { action: "spawn", name: "scribe", agent: "code-reviewer" });
    await assert.rejects(call(h, { action: "send", name: "reviewer", message: "review" }));

    const errors: string[] = [];
    const originalWrite = process.stderr.write.bind(process.stderr);
    process.stderr.write = ((chunk: string) => {
      errors.push(String(chunk));
      return true;
    }) as typeof process.stderr.write;
    try {
      await h.handlers.get("session_shutdown")?.({}, h.ctx);
    } finally {
      process.stderr.write = originalWrite;
    }

    assert.equal(h.spawned[0]!.session.disposed, 1);
    assert.equal(h.spawned[1]!.session.disposed, 1);
    const line = errors.join("");
    assert.match(line, /1 teammate\(s\) ended with undelivered work/);
    assert.match(line, /reviewer .* -> \/tmp-fake\/reviewer\.jsonl/);
  });

  it("refuses everything before session_start rather than half-working", async () => {
    const h = harness({});
    await assert.rejects(call(h, { action: "list" }), /not ready/);
  });
});
