/**
 * `config/routing.json` — or, on a clone where the installer has not run, the tracked
 * `config/routing.default.json` it is generated from — read as raw JSON, for the modules that
 * need one block out of it.
 *
 * `extensions/dispatch/config.ts` already reads this file and validates all of it — tiers, egress,
 * concurrency — and returns a `RoutingConfig` plus a problem list that makes dispatch refuse to
 * run. That loader is not reused here, and the reason is layering rather than taste: `lib/` is
 * imported by every extension in this tree and imports none of them back, so a module in `lib/`
 * that pulled `extensions/dispatch/config.ts` in would make `EXT-13`'s provider path and `EXT-20`'s
 * titling depend on `EXT-05` loading cleanly. It would also inherit dispatch's failure semantics,
 * which are deliberately harsh (*an unusable `routing.json` refuses all dispatch*) and wrong for a
 * caller whose worst case is "keep the built-in default".
 *
 * So: the same search order, the same env override, no validation beyond "it is a JSON object",
 * and every caller decides for itself what a missing block means.
 */
import { existsSync, readFileSync, realpathSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { repoRoot } from "./paths.ts";

export interface RoutingFile {
  /** The parsed object, or `undefined` when the file is absent, unparseable or not an object. */
  readonly raw: Record<string, unknown> | undefined;
  /** The path that was read, or `<absent>`. Named in every notice so a reader can check it. */
  readonly source: string;
  /** Why `raw` is undefined. Absent when the file was read. */
  readonly problem?: string;
}

/**
 * The tracked template `routing.json` is generated from by `scripts/install.sh`.
 *
 * `dispatch/config.ts` deliberately does NOT fall back to it, and says so: dispatch spends money
 * on whatever the tier map names, and doing that from a routing table nobody chose is worse than
 * refusing. The two callers here are the opposite case — auto-title picks the model for a six-word
 * throwaway, provider-retry reads one integer — and for them the shipped template is a better
 * answer than "no titles and no retries until you run the installer". `config/routing.json` is
 * git-ignored, so on a fresh clone it is also the only answer that is not a guess: the template is
 * exactly what the installer will copy.
 */
const ROUTING_TEMPLATE = "routing.default.json";

/**
 * Candidate locations, first existing wins — the same order and the same realpath step as
 * `dispatch/config.ts`'s `configPaths`, because `extensions/` is a symlink into
 * `~/.pi/agent/extensions` and `import.meta.url` therefore points at the symlink, not at the repo.
 *
 * Both roots are searched for the generated `routing.json` before either is searched for
 * {@link ROUTING_TEMPLATE}. That ordering matters rather than being tidy: a generated file in the
 * *other* root still records a choice an operator made, and the template records none.
 */
export function routingPaths(override?: string): string[] {
  if (override) return [override];
  const roots: string[] = [];
  try {
    const here = realpathSync(fileURLToPath(import.meta.url));
    roots.push(resolve(dirname(here), "..", ".."));
  } catch {
    // A distribution that cannot realpath its own module falls through to repoRoot().
  }
  roots.push(repoRoot());
  return [
    ...roots.map((root) => resolve(root, "config", "routing.json")),
    ...roots.map((root) => resolve(root, "config", ROUTING_TEMPLATE)),
  ];
}

/** `PI_ROUTING_CONFIG` is the same test seam `dispatch/config.ts` honours. */
export function readRoutingFile(override = process.env.PI_ROUTING_CONFIG): RoutingFile {
  // An override that does not exist is a typo, not a hint: falling through to the repo's own file
  // would silently load a different one than the one that was named.
  if (override !== undefined && override !== "" && !existsSync(override)) {
    return { raw: undefined, source: override, problem: `routing.json was pinned to "${override}", which does not exist` };
  }
  const candidates = routingPaths(override);
  const found = candidates.find((p) => existsSync(p));
  if (found === undefined) {
    return {
      raw: undefined,
      source: "<absent>",
      problem:
        `neither routing.json nor ${ROUTING_TEMPLATE} was found (looked in: ${candidates.join(", ")}) — ` +
        `routing.json is generated by scripts/install.sh from config/${ROUTING_TEMPLATE}`,
    };
  }
  let parsed: unknown;
  try {
    parsed = JSON.parse(readFileSync(found, "utf8"));
  } catch (err) {
    return { raw: undefined, source: found, problem: `${found} is not valid JSON: ${(err as Error).message}` };
  }
  if (parsed === null || typeof parsed !== "object" || Array.isArray(parsed)) {
    return { raw: undefined, source: found, problem: `${found} must be a JSON object` };
  }
  return { raw: parsed as Record<string, unknown>, source: found };
}

/**
 * `tiers.<name>.model` as a bare `provider/id`, or `undefined`.
 *
 * Reads only what it needs: a caller asking for one tier must not be made to depend on every
 * other tier in the file being well formed.
 */
export function tierModel(routing: RoutingFile, tier: string): string | undefined {
  const tiers = routing.raw?.tiers;
  if (tiers === null || typeof tiers !== "object" || Array.isArray(tiers)) return undefined;
  const row = (tiers as Record<string, unknown>)[tier];
  if (row === null || typeof row !== "object" || Array.isArray(row)) return undefined;
  const model = (row as Record<string, unknown>).model;
  return typeof model === "string" && model.includes("/") ? model : undefined;
}
