/**
 * Resolves a `config/routing.json` tier name (e.g. `"cheap"`) to a provider-qualified
 * model id (e.g. `"github-copilot/claude-haiku-4.5"`) — the same lookup `config/bin/pi-tier`
 * does in shell,
 * kept here as its TypeScript twin because `bin/pi-digest-drain` needs it in-process rather
 * than as a second spawn.
 *
 * Ownership note: a shared `tiers.ts` is EXT-05 territory
 * ("tier → provider/id mapping"), and EXT-05 had not landed a `lib/tiers.ts` at the time this
 * module was written. This is `EXT-06`'s own copy, scoped to `extensions/digest/`, not a claim
 * on that shared module — the de-duplication is left for integration.
 */
import { readFile } from "node:fs/promises";
import { routingConfigPath } from "./paths.ts";

export class UnknownTierError extends Error {
  readonly tier: string;
  readonly routingPath: string;
  constructor(tier: string, routingPath: string) {
    super(`unknown tier "${tier}" in ${routingPath} — refusing to guess (try pi-tier --list)`);
    this.name = "UnknownTierError";
    this.tier = tier;
    this.routingPath = routingPath;
  }
}

interface RoutingFile {
  tiers?: Record<string, { model?: unknown }>;
}

/**
 * @throws UnknownTierError when the tier is absent — never falls back to a different tier or
 *   a hardcoded model (REQ-PRV-32: a misconfigured digest must fail loud, not summarise on the
 *   wrong model silently).
 */
export async function resolveTier(tier: string, routingPath: string = routingConfigPath()): Promise<string> {
  let raw: string;
  try {
    raw = await readFile(routingPath, "utf8");
  } catch (err) {
    // routing.json is generated by scripts/install.sh from config/routing.default.json and is
    // git-ignored, so "absent" is the normal state of a fresh clone rather than a corruption.
    throw new Error(
      `could not read ${routingPath} to resolve tier "${tier}": ${(err as Error).message}. ` +
        `routing.json is generated by scripts/install.sh from config/routing.default.json — run scripts/install.sh`,
      { cause: err },
    );
  }

  let parsed: RoutingFile;
  try {
    parsed = JSON.parse(raw) as RoutingFile;
  } catch (err) {
    throw new Error(`${routingPath} is not valid JSON: ${(err as Error).message}`, { cause: err });
  }

  const model = parsed.tiers?.[tier]?.model;
  if (typeof model !== "string" || model.length === 0) {
    throw new UnknownTierError(tier, routingPath);
  }
  return model;
}
