/**
 * EXT-33 — `/autocompact`: the declared threshold follows the model's declared window.
 *
 * What is unit-testable here is the whole chain minus the command handler itself, which needs a
 * live PI session: the catalogue reader, the id -> window lookup, the pure config transform, and
 * the writer's two promised properties — one line changes, and the file's mode does not.
 *
 * The last test pins the *arithmetic* the handler performs, which is the one thing about it that
 * is a decision rather than plumbing: it writes `contextWindow - reserveTokens`, because writing
 * the window itself would state an intent `thresholdReport()` can only ever call
 * `window-too-small`. That is cheap to reverse by accident and expensive to notice, so it fails
 * here instead.
 */
import assert from "node:assert/strict";
import {
  copyFileSync,
  mkdtempSync,
  readdirSync,
  readFileSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { test } from "node:test";
import {
  replaceAbsoluteTokensText,
  withAbsoluteTokens,
  writeAbsoluteTokens,
} from "../../extensions/compaction/index.ts";
import {
  declaredContextWindows,
  findContextWindow,
  thresholdReport,
  PI_DEFAULT_RESERVE_TOKENS,
} from "../../extensions/compaction/threshold.ts";
import { shippedConfig } from "../lib/repo-config.ts";

const CONFIG_PATH = fileURLToPath(new URL("../../config/compaction.json", import.meta.url));
// `config/models.json` is generated by the installer and git-ignored, so a clean checkout has only
// the tracked template. `shippedConfig` prefers it, which is what makes these assertions the same
// on a fresh clone as on an installed tree.
const MODELS_PATH = shippedConfig("models");

function scratch(): string {
  return mkdtempSync(join(tmpdir(), "pi-autocompact-"));
}

test("declaredContextWindows reads both catalogue shapes", () => {
  const windows = declaredContextWindows({
    providers: {
      alpha: { modelOverrides: { "m-1": { contextWindow: 200000 } } },
      beta: { models: [{ id: "m-2", contextWindow: 220000 }] },
    },
  });
  assert.deepEqual(windows, [
    { provider: "alpha", model: "m-1", contextWindow: 200000, declaredIn: "modelOverrides" },
    { provider: "beta", model: "m-2", contextWindow: 220000, declaredIn: "models" },
  ]);
});

test("declaredContextWindows skips what it cannot use instead of throwing", () => {
  const windows = declaredContextWindows({
    providers: {
      alpha: {
        models: [
          { id: "no-window" },
          { contextWindow: 1000 },
          { id: "zero", contextWindow: 0 },
          { id: "text", contextWindow: "200000" },
          { id: "good", contextWindow: 128000 },
        ],
        modelOverrides: { broken: null },
      },
      beta: "not an object",
    },
  });
  assert.deepEqual(windows.map((w) => w.model), ["good"]);
});

test("declaredContextWindows is total over junk input", () => {
  for (const raw of [null, undefined, 42, "x", {}, { providers: null }, { providers: [] }]) {
    assert.deepEqual(declaredContextWindows(raw), []);
  }
});

test("findContextWindow resolves a uniquely declared id", () => {
  const windows = declaredContextWindows(JSON.parse(readFileSync(MODELS_PATH, "utf8")));
  const found = findContextWindow(windows, "claude-opus-5");
  assert.equal(found.ok, true);
  assert.equal(found.ok && found.window.contextWindow, 200000);
});

test("findContextWindow names the declared ids when the model is unknown", () => {
  const windows = declaredContextWindows(JSON.parse(readFileSync(MODELS_PATH, "utf8")));
  const found = findContextWindow(windows, "gpt-2");
  assert.equal(found.ok, false);
  assert.match(found.ok ? "" : found.reason, /declares no contextWindow for "gpt-2"/);
  assert.match(found.ok ? "" : found.reason, /claude-opus-5/);
});

test("findContextWindow refuses an id two providers declare differently, and the session's provider settles it", () => {
  // Not hypothetical: an installed tree that adds the litellm fragment alongside github-copilot
  // declares gpt-5.6-sol at 200000 under one and 220000 under the other. The shipped template has
  // a single provider, so the collision is built here rather than depending on how this machine
  // happens to be installed. Guessing would persist the wrong number.
  const windows = declaredContextWindows({
    providers: {
      "github-copilot": { modelOverrides: { "gpt-5.6-sol": { contextWindow: 200000 } } },
      litellm: { models: [{ id: "gpt-5.6-sol", contextWindow: 220000 }] },
    },
  });
  const ambiguous = findContextWindow(windows, "gpt-5.6-sol");
  assert.equal(ambiguous.ok, false);
  assert.match(ambiguous.ok ? "" : ambiguous.reason, /2 providers/);

  const settled = findContextWindow(windows, "gpt-5.6-sol", "litellm");
  assert.equal(settled.ok, true);
  assert.equal(settled.ok && settled.window.contextWindow, 220000);
});

test("withAbsoluteTokens replaces one number and carries everything else through", () => {
  const raw = JSON.parse(readFileSync(CONFIG_PATH, "utf8")) as Record<string, unknown>;
  const next = withAbsoluteTokens(raw, 200000) as {
    compaction: { threshold: Record<string, unknown>; pinned: unknown; loopGuard: unknown };
  };
  assert.equal(next.compaction.threshold.absoluteTokens, 200000);
  assert.equal(next.compaction.threshold.toleranceRatio, 0.2);
  assert.deepEqual(next.compaction.pinned, (raw.compaction as Record<string, unknown>).pinned);
  assert.deepEqual(next.compaction.loopGuard, (raw.compaction as Record<string, unknown>).loopGuard);
});

test("withAbsoluteTokens does not mutate its input, and creates only the nesting it needs", () => {
  const raw = { compaction: { pinned: { enabled: true } } };
  const next = withAbsoluteTokens(raw, 128000) as { compaction: { threshold: Record<string, unknown> } };
  assert.deepEqual(next.compaction.threshold, { absoluteTokens: 128000 });
  assert.deepEqual(raw, { compaction: { pinned: { enabled: true } } });
  assert.deepEqual(withAbsoluteTokens(null, 10), { compaction: { threshold: { absoluteTokens: 10 } } });
  // A threshold that is not an object is replaced, never spread character by character.
  assert.deepEqual(withAbsoluteTokens({ compaction: { threshold: "180000" } }, 10), {
    compaction: { threshold: { absoluteTokens: 10 } },
  });
});

test("writeAbsoluteTokens changes exactly one line of the shipped config and keeps its mode", () => {
  const dir = scratch();
  try {
    const path = join(dir, "compaction.json");
    copyFileSync(CONFIG_PATH, path);
    const before = readFileSync(path, "utf8");
    const mode = statSync(path).mode;

    writeAbsoluteTokens(path, 200000);

    const after = readFileSync(path, "utf8");
    assert.equal(statSync(path).mode, mode);
    assert.ok(after.endsWith("}\n"));
    const changed = after
      .split("\n")
      .map((line, i) => [line, before.split("\n")[i]] as const)
      .filter(([now, was]) => now !== was);
    assert.equal(changed.length, 1);
    assert.match(changed[0]![0]!, /"absoluteTokens": 200000/);
    assert.equal(
      (JSON.parse(after) as { compaction: { threshold: { absoluteTokens: number } } }).compaction
        .threshold.absoluteTokens,
      200000,
    );
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test("replaceAbsoluteTokensText refuses anything it cannot verify", () => {
  // No key to patch, two keys to patch, and a patch that would not parse: each falls back.
  assert.equal(replaceAbsoluteTokensText('{"compaction":{}}', 10), undefined);
  assert.equal(
    replaceAbsoluteTokensText('{"a":{"absoluteTokens":1},"b":{"absoluteTokens":2}}', 10),
    undefined,
  );
  assert.equal(replaceAbsoluteTokensText('{"absoluteTokens": 1', 10), undefined);
  // Right shape, wrong place: patched cleanly, but not where the config is read from.
  assert.equal(replaceAbsoluteTokensText('{"threshold":{"absoluteTokens":1}}', 10), undefined);
});

test("writeAbsoluteTokens adds the key when the config has none, and stays valid", () => {
  const dir = scratch();
  try {
    const path = join(dir, "compaction.json");
    writeFileSync(path, '{\n  "compaction": {\n    "pinned": { "enabled": false }\n  }\n}\n');
    writeAbsoluteTokens(path, 136000);
    const parsed = JSON.parse(readFileSync(path, "utf8")) as {
      compaction: { threshold: { absoluteTokens: number }; pinned: { enabled: boolean } };
    };
    assert.equal(parsed.compaction.threshold.absoluteTokens, 136000);
    assert.equal(parsed.compaction.pinned.enabled, false);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test("writeAbsoluteTokens leaves no temp file behind and is idempotent", () => {
  const dir = scratch();
  try {
    const path = join(dir, "compaction.json");
    writeFileSync(path, '{"compaction":{"threshold":{"absoluteTokens":1}}}\n');
    writeAbsoluteTokens(path, 200000);
    const once = readFileSync(path, "utf8");
    writeAbsoluteTokens(path, 200000);
    assert.equal(readFileSync(path, "utf8"), once);
    assert.deepEqual(readdirSync(dir), ["compaction.json"]);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test("/autocompact writes window - reserve, which is the only value that reads as aligned", () => {
  const tolerance = 0.2;
  const reserve = PI_DEFAULT_RESERVE_TOKENS;
  for (const window of [200000, 128000, 64000, 32000]) {
    // What the command writes: the trigger itself, stated. Exact, so it cannot drift out of it.
    const written = thresholdReport(window, reserve, window - reserve, tolerance);
    assert.equal(written.verdict, "aligned", `window ${window} must read as aligned`);
    assert.equal(written.divergenceRatio, 0);
    assert.equal(written.effectiveTrigger, written.configuredAbsolute);
  }
  // The literal reading of "set it to the context window", for contrast: PI's trigger is always
  // below it, so the verdict is window-too-small — and on a small window it is loudly so, with a
  // remedy line that correctly says no PI 0.84.0 setting closes the gap.
  const literal = thresholdReport(64000, reserve, 64000, tolerance);
  assert.equal(literal.verdict, "window-too-small");
});
