/**
 * `EXT-30` — `config/trusted-roots.json` loading.
 *
 * The load path has exactly one job it must never get wrong: a file it cannot understand must
 * shrink the trusted set to nothing, loudly, and never grow it. Every failure case below asserts
 * both halves — `roots: []` and a non-empty `problem`.
 */
import { shippedConfig } from "../lib/repo-config.ts";
import assert from "node:assert/strict";
import { homedir } from "node:os";
import { join, resolve, sep } from "node:path";
import { afterEach, describe, it } from "node:test";
import {
  TrustConfigError,
  expandRoot,
  isUnder,
  loadTrustedRoots,
  parseTrustedRoots,
  trustedRootsPaths,
} from "../../extensions/trust.ts";
import { writeRootsFile } from "./helpers.ts";

afterEach(() => {
  delete process.env.PI_TRUSTED_ROOTS;
});

/**
 * `config/trusted-roots.json` is generated by `scripts/install.sh` from
 * `config/trusted-roots.default.json` and is git-ignored, so a clean checkout carries only the
 * template. `shippedConfig()` resolves to whichever the checkout has; both must load clean, because the
 * installer copies one to the other and `extensions/trust.ts` reads the result verbatim.
 */
const SHIPPED_ROOTS = shippedConfig("trusted-roots");

describe("loadTrustedRoots — the shipped file", () => {
  it("loads the shipped roots file and is not degraded", () => {
    const config = loadTrustedRoots(SHIPPED_ROOTS);
    assert.equal(config.degraded, false, config.problem);
    assert.equal(config.problem, undefined);
    assert.match(config.source, /config\/trusted-roots(\.default)?\.json$/);
  });

  it("declares only tilde-relative roots, and every one expands to an absolute path", () => {
    // The root *names* are deliberately not pinned: the shipped template declares a generic pair and
    // the installer rewrites the list from the operator's answers, so an exact-list assertion would
    // encode one machine's directory layout into the public repository. What must hold either way is
    // the shape — a non-empty list, no literal tilde left after expansion, nothing relative.
    const config = loadTrustedRoots(SHIPPED_ROOTS);
    assert.ok(config.declared.length > 0, "the shipped file must declare at least one root");
    for (const declared of config.declared) {
      assert.ok(
        declared.startsWith("~/") || declared.startsWith(sep),
        `${declared} must be written as ~/… or as an absolute path`,
      );
    }
    assert.ok(config.roots.length > 0, "the shipped roots must resolve to at least one path");
    for (const root of config.roots) {
      assert.ok(root.startsWith(sep), `${root} must be absolute after expansion`);
      assert.ok(!root.startsWith("~"), `${root} must not keep a literal tilde`);
    }
  });

  it("honours PI_TRUSTED_ROOTS ahead of the shipped file", () => {
    const file = writeRootsFile({ version: 1, roots: ["/srv/declared"] });
    process.env.PI_TRUSTED_ROOTS = file;
    assert.equal(trustedRootsPaths()[0], file);
    const config = loadTrustedRoots();
    assert.equal(config.source, file);
    assert.deepEqual([...config.roots], ["/srv/declared"]);
  });
});

describe("loadTrustedRoots — failure is fail-closed and loud", () => {
  it("an override that does not exist trusts nothing — it does not fall back to the shipped file", () => {
    const config = loadTrustedRoots(join(sep, "nonexistent", "trusted-roots.json"));
    assert.deepEqual([...config.roots], []);
    assert.equal(config.degraded, true);
    assert.match(config.problem ?? "", /does not exist/);
    assert.match(config.problem ?? "", /NOTHING is auto-trusted/);
  });

  it("the same applies to PI_TRUSTED_ROOTS — a typo must never widen the trusted set", () => {
    process.env.PI_TRUSTED_ROOTS = join(sep, "nonexistent", "typo.json");
    const config = loadTrustedRoots();
    assert.deepEqual([...config.roots], []);
    assert.equal(config.degraded, true);
    assert.match(config.problem ?? "", /does not exist/);
  });

  it("malformed JSON trusts nothing and says so", () => {
    const config = loadTrustedRoots(writeRootsFile("{ not json"));
    assert.deepEqual([...config.roots], []);
    assert.equal(config.degraded, true);
    assert.match(config.problem ?? "", /not valid JSON/);
  });

  it("a top-level array is a TrustConfigError, reported verbatim rather than swallowed", () => {
    const config = loadTrustedRoots(writeRootsFile(["~/code"]));
    assert.deepEqual([...config.roots], []);
    assert.equal(config.degraded, true);
    assert.match(config.problem ?? "", /TrustConfigError/);
    assert.match(config.problem ?? "", /must be a JSON object/);
  });

  it("a missing roots array is a TrustConfigError", () => {
    const config = loadTrustedRoots(writeRootsFile({ version: 1 }));
    assert.deepEqual([...config.roots], []);
    assert.equal(config.degraded, true);
    assert.match(config.problem ?? "", /must carry a "roots" array/);
  });

  it("non-string entries are dropped, and the surviving entries still apply", () => {
    const config = loadTrustedRoots(writeRootsFile({ version: 1, roots: ["/srv/ok", 7, ""] }));
    assert.deepEqual([...config.roots], ["/srv/ok"]);
    assert.equal(config.degraded, true);
    assert.match(config.problem ?? "", /roots\[1\] is not a non-empty string/);
    assert.match(config.problem ?? "", /roots\[2\] is not a non-empty string/);
  });
});

describe("parseTrustedRoots — audit finding 29 cannot be smuggled back in", () => {
  it("refuses the filesystem root", () => {
    const parsed = parseTrustedRoots({ roots: ["/", "/srv/ok"] }, "<test>");
    assert.deepEqual(parsed.roots, ["/srv/ok"]);
    assert.match(parsed.problems[0] ?? "", /the filesystem root/);
    assert.match(parsed.problems[0] ?? "", /audit finding 29/);
  });

  it("refuses the home directory, tilde or spelled out", () => {
    for (const entry of ["~", "~/", homedir()]) {
      const parsed = parseTrustedRoots({ roots: [entry] }, "<test>");
      assert.deepEqual(parsed.roots, [], entry);
      assert.match(parsed.problems[0] ?? "", /the home directory/, entry);
    }
  });

  it("throws TrustConfigError, not a generic Error, on a structural failure", () => {
    assert.throws(() => parseTrustedRoots(null, "<test>"), TrustConfigError);
    assert.throws(() => parseTrustedRoots({ roots: "~/code" }, "<test>"), (err: unknown) => {
      assert.ok(err instanceof TrustConfigError);
      assert.equal(err.name, "TrustConfigError");
      assert.equal(err.source, "<test>");
      return true;
    });
  });

  it("dedupes roots that resolve to the same place", () => {
    const parsed = parseTrustedRoots({ roots: ["/srv/ok", "/srv/ok/", "/srv/./ok"] }, "<test>");
    assert.deepEqual(parsed.roots, ["/srv/ok"]);
    assert.deepEqual(parsed.problems, []);
  });
});

describe("expandRoot / isUnder", () => {
  it("expands a leading tilde against $HOME", () => {
    assert.equal(expandRoot("~/does-not-exist-xyz"), resolve(homedir(), "does-not-exist-xyz"));
  });

  it("keeps a path that does not exist yet rather than dropping it", () => {
    const absent = join(sep, "srv", "not-created-yet-xyz");
    assert.equal(expandRoot(absent), absent);
  });

  it("matches only at a path-segment boundary", () => {
    assert.equal(isUnder("/a/b", "/a/b"), true);
    assert.equal(isUnder("/a/b/c", "/a/b"), true);
    assert.equal(isUnder("/a/bc", "/a/b"), false, "/a/bc is NOT under /a/b");
    assert.equal(isUnder("/a", "/a/b"), false);
    assert.equal(isUnder("/a/b/c", "/a/b/"), true, "a trailing separator must not change the answer");
  });
});
